"""
Static ensemble for network anomaly detection.
"""

from __future__ import annotations

from typing import Mapping

import numpy as np

from src.ensemble.score_combiner import ScoreCombiner


class StaticEnsemble:
    """
    Fixed-weight anomaly detection ensemble.

    The weights remain constant for every sample.

    Example:
        IF       = 0.25
        LOF      = 0.25
        OCSVM    = 0.25
        AE       = 0.25

    The ensemble can later share the same ScoreCombiner with
    the Adaptive RL Ensemble, where RL dynamically supplies
    the weights.
    """

    def __init__(
        self,
        weights: Mapping[str, float],
        normalization: str = "minmax",
        threshold: float | None = None,
    ) -> None:

        self.combiner = ScoreCombiner(
            weights=weights,
            normalization=normalization,
        )

        self.threshold = threshold
        self.is_fitted = False

    # ------------------------------------------------------------------
    # Fitting
    # ------------------------------------------------------------------

    def fit(
        self,
        validation_scores: Mapping[str, np.ndarray],
        y_validation: np.ndarray,
        threshold_strategy: str = "percentile",
        threshold_percentile: float = 95.0,
    ) -> "StaticEnsemble":
        """
        Fit the ensemble using development/validation data.

        This does NOT train the four underlying anomaly detectors.

        It only:
            1. Fits score normalization.
            2. Determines the ensemble threshold.

        Args:
            validation_scores:
                Scores generated by the four already-trained models.

            y_validation:
                Binary validation labels:
                    0 = normal
                    1 = anomaly

            threshold_strategy:
                Currently supported:
                    - percentile

            threshold_percentile:
                Percentile used to determine the anomaly threshold.

        Returns:
            Self.
        """

        y_validation = np.asarray(y_validation)

        if y_validation.ndim != 1:
            raise ValueError(
                "y_validation must be one-dimensional."
            )

        if len(y_validation) != self._score_length(
            validation_scores
        ):
            raise ValueError(
                "Validation scores and labels must have "
                "the same number of samples."
            )

        unique_labels = np.unique(y_validation)

        if not np.all(np.isin(unique_labels, [0, 1])):
            raise ValueError(
                "y_validation must contain only binary labels "
                "0 and 1."
            )

        if not 0.0 < threshold_percentile < 100.0:
            raise ValueError(
                "threshold_percentile must be between 0 and 100."
            )

        self.combiner.fit(validation_scores)

        validation_ensemble_scores = self.combiner.combine(
            validation_scores
        )

        if threshold_strategy == "percentile":

            # Threshold is determined from NORMAL validation
            # samples only. This prevents the attack distribution
            # from directly determining the anomaly threshold.
            normal_scores = validation_ensemble_scores[
                y_validation == 0
            ]

            if len(normal_scores) == 0:
                raise ValueError(
                    "Validation set contains no normal samples."
                )

            self.threshold = float(
                np.percentile(
                    normal_scores,
                    threshold_percentile,
                )
            )

        else:
            raise ValueError(
                f"Unsupported threshold strategy: "
                f"{threshold_strategy}"
            )

        self.is_fitted = True

        return self

    # ------------------------------------------------------------------
    # Prediction
    # ------------------------------------------------------------------

    def anomaly_score(
        self,
        scores: Mapping[str, np.ndarray],
    ) -> np.ndarray:
        """
        Generate combined anomaly scores.
        """

        if not self.is_fitted:
            raise RuntimeError(
                "StaticEnsemble must be fitted before "
                "generating anomaly scores."
            )

        return self.combiner.combine(scores)

    def predict(
        self,
        scores: Mapping[str, np.ndarray],
    ) -> np.ndarray:
        """
        Convert ensemble anomaly scores into binary predictions.

        Returns:
            int8 array:
                0 = normal
                1 = anomaly
        """

        if self.threshold is None:
            raise RuntimeError(
                "Ensemble threshold has not been fitted."
            )

        scores_combined = self.anomaly_score(scores)

        return (
            scores_combined >= self.threshold
        ).astype(np.int8)

    # ------------------------------------------------------------------
    # Utilities
    # ------------------------------------------------------------------

    @staticmethod
    def _score_length(
        scores: Mapping[str, np.ndarray],
    ) -> int:
        """Validate score arrays and return their length."""

        lengths = {
            name: len(np.asarray(values))
            for name, values in scores.items()
        }

        if set(lengths.keys()) != {
            "if",
            "lof",
            "svm",
            "ae",
        }:
            raise ValueError(
                "Scores must contain if, lof, svm, and ae."
            )

        if len(set(lengths.values())) != 1:
            raise ValueError(
                f"All score arrays must have the same length. "
                f"Got {lengths}."
            )

        return next(iter(lengths.values()))

    def get_weights(self) -> dict[str, float]:
        """Return current static weights."""

        return self.combiner.get_weights()

    def get_threshold(self) -> float:
        """Return fitted anomaly threshold."""

        if self.threshold is None:
            raise RuntimeError(
                "Threshold has not been fitted."
            )

        return float(self.threshold)